version: '3.3'
services: 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
  db:
    image: bitnami/postgresql:12.5.0
    environment:
      POSTGRESQL_USERNAME: ${PGUSERNAME}
      POSTGRESQL_PASSWORD: ${PGPASSWORD}
    volumes:
      - postgres-vol:/bitnami/postgresql
    restart: unless-stopped
  rtpproxy1:
    build: ./rtpproxy
    image: adeshpandey/rtpproxy
    ports:
      - 10000-10020:10000-10020/udp
    environment:
      - PUBLIC_IP=${PUBLIC_IP}
      - START_PORT=10000
      - END_PORT=10020
  rtpproxy2:
    image: adeshpandey/rtpproxy
    ports:
      - 10021-10040:10021-10040/udp
    environment:
      - PUBLIC_IP=${PUBLIC_IP}
      - START_PORT=10021
      - END_PORT=10040
    depends_on:
      - rtpproxy1
  rtpengine:
    build: ./rtpengine
    image: adeshpandey/rtpengine
    ports:
      - 10041-11000:10041-11000/udp
    environment:
      - PUBLIC_IP=${PUBLIC_IP}
      - START_PORT=10021
      - END_PORT=11000
    depends_on:
      - rtpproxy1
  kamailio:
    build: ./kamailio
    restart: unless-stopped
    environment:
      - PGPASSWORD=${PGPASSWORD}
    volumes:
      - ./kamailio/kamctlrc:/etc/kamailio/kamctlrc
      - ./kamailio/modules.cfg:/etc/kamailio/modules.cfg
      - ./kamailio/kamailio.cfg:/etc/kamailio/kamailio.cfg
      - ./kamailio/tls.cfg:/etc/kamailio/tls.cfg
      - ./kamailio/tls/kamailio.crt:/etc/kamailio/kamailio.crt
      - ./kamailio/tls/kamailio.key:/etc/kamailio/kamailio.key
    ports:
      - 8060:8060
      - 8082:8082
      - 8083:8083
    depends_on:
      - db
      - rtpengine
    command: "-l udp:0.0.0.0:8060/${PUBLIC_IP}:8060 -l tcp:0.0.0.0:8060/${PUBLIC_IP}:8060 -l tls:0.0.0.0:8082/${PUBLIC_IP}:8082"
  # webapp:
  #   image: nginx
  #   volumes:
  #     - ./sip-interface/build:/usr/share/nginx/html
  #     - ./webapp/tls:/etc/nginx/certs
  #     - ./webapp/default.conf:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - 80:80
  #     - 443:443
volumes:
  postgres-vol:

networks:
  default:
    external: true
    name: unifonic-voice-network