version: '3.9'

services: 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
  db:
    image: bitnami/postgresql:12.5.0
    environment:
      POSTGRESQL_USERNAME: ${PGUSERNAME}
      POSTGRESQL_PASSWORD: ${PGPASSWORD}
    volumes:
      - postgres-vol:/bitnami/postgresql
    restart: unless-stopped
  rtpproxy:
    build: ./rtpproxy
    image: adeshpandey/rtpproxy
    ports:
      - 10000-10020:10000-10020/udp
    environment:
      - PUBLIC_IP=${PUBLIC_IP}
      - START_PORT=10000
      - END_PORT=10020
  kamailio:
    image: 'kamailio/kamailio:5.2.3-bionic'
    restart: unless-stopped
    volumes:
      - ./kamailio/kamctlrc:/etc/kamailio/kamctlrc
      - ./kamailio/kamailio.cfg:/etc/kamailio/kamailio.cfg
    ports:
      - 5060:5060
    depends_on:
      - db
      - rtpproxy
    command: "-l udp:0.0.0.0:5060/${PUBLIC_IP}:5060 -l tcp:0.0.0.0:5060/${PUBLIC_IP}"
volumes:
  postgres-vol: