apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f k8s-compose.yml -o k8s/
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f k8s-compose.yml -o k8s/
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: db
    spec:
      containers:
        - env:
            - name: POSTGRESQL_PASSWORD
              value: kamailio
            - name: POSTGRESQL_USERNAME
              value: kamailio
          image: bitnami/postgresql:12.5.0
          name: db
          ports:
            - containerPort: 5432
          resources: {}
          volumeMounts:
            - mountPath: /bitnami/postgresql
              name: postgres-vol
      restartPolicy: Always
      volumes:
        - name: postgres-vol
          persistentVolumeClaim:
            claimName: postgres-vol
status: {}
