apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f k8s-compose.yml -o k8s/
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: kamailio
  name: kamailio
spec:
  type: NodePort
  ports:
    - name: "5060"
      port: 5060
      targetPort: 5060
    - name: "8082"
      port: 8082
      targetPort: 8082
    - name: "8083"
      port: 8083
      targetPort: 8083
  selector:
    io.kompose.service: kamailio
status:
  loadBalancer: {}
